// ─── City Event Templates ───
// 12 events that can fire during city simulation, affecting sectors and player.

import type { CityEvent } from "./types";

export const CITY_EVENT_TEMPLATES: CityEvent[] = [
  // ── Tech / IT ──
  {
    id: "ai_investment_surge",
    emoji: "🤖",
    titleFa: "موج سرمایه‌گذاری هوش مصنوعی",
    descriptionFa: "شرکت‌های بزرگ روی استارت‌آپ‌های AI سرمایه‌گذاری کردن. نیاز به برنامه‌نویس جهش زده.",
    severity: "major",
    affectedSectors: ["tech", "finance"],
    sectorHealthDelta: +3,
    salaryImpact: +0.12,
    jobDemandDelta: +8,
    investmentImpact: +0.2,
    durationDays: 4,
    triggerWaves: ["tech_boom", "stability"],
    missionEventTag: "tech_boom_event",
  },
  {
    id: "tech_layoffs",
    emoji: "💼",
    titleFa: "اخراج دسته‌جمعی IT",
    descriptionFa: "چند شرکت بزرگ IT تعدیل نیرو کردن. بازار کار تکنیک سرد شده.",
    severity: "crisis",
    affectedSectors: ["tech"],
    sectorHealthDelta: -4,
    salaryImpact: -0.15,
    jobDemandDelta: -10,
    investmentImpact: -0.1,
    durationDays: 5,
    triggerWaves: ["recession"],
    missionEventTag: "job_crisis_event",
  },

  // ── Finance / Economy ──
  {
    id: "dollar_spike",
    emoji: "💵",
    titleFa: "جهش ارزی",
    descriptionFa: "نرخ دلار ناگهان بالا رفت. قیمت‌ها داره می‌ره بالا اما سرمایه‌گذاری دلاری پربازده‌تره.",
    severity: "major",
    affectedSectors: ["finance", "retail", "manufacturing"],
    sectorHealthDelta: -2,
    salaryImpact: -0.05,
    jobDemandDelta: -3,
    investmentImpact: +0.3,
    durationDays: 6,
    missionEventTag: "dollar_rise_event",
  },
  {
    id: "stock_crash",
    emoji: "📉",
    titleFa: "سقوط بازار سهام",
    descriptionFa: "بازار بورس امروز ریخت. سرمایه‌گذاری‌های کوتاه‌مدت ضرر کردن.",
    severity: "crisis",
    affectedSectors: ["finance"],
    sectorHealthDelta: -5,
    salaryImpact: -0.08,
    jobDemandDelta: -5,
    investmentImpact: -0.25,
    durationDays: 4,
    triggerWaves: ["recession"],
    missionEventTag: "market_crash_event",
  },
  {
    id: "banking_bonus",
    emoji: "🏦",
    titleFa: "سود بانکی بالاست",
    descriptionFa: "بانک مرکزی نرخ سود رو افزایش داد. پس‌انداز کردن الان مزیت داره.",
    severity: "minor",
    affectedSectors: ["finance"],
    sectorHealthDelta: +2,
    salaryImpact: +0.02,
    jobDemandDelta: +2,
    investmentImpact: +0.1,
    durationDays: 3,
    missionEventTag: "savings_bonus_event",
  },

  // ── Construction / Real Estate ──
  {
    id: "housing_boom",
    emoji: "🏘️",
    titleFa: "رونق مسکن",
    descriptionFa: "قیمت مسکن داره بالا می‌ره. بازار ساخت‌وساز داغ شده.",
    severity: "major",
    affectedSectors: ["construction", "manufacturing"],
    sectorHealthDelta: +3,
    salaryImpact: +0.1,
    jobDemandDelta: +6,
    investmentImpact: +0.15,
    durationDays: 5,
    triggerWaves: ["construction_surge", "finance_bull"],
    missionEventTag: "construction_boom_event",
  },
  {
    id: "infrastructure_project",
    emoji: "🛣️",
    titleFa: "پروژه زیرساختی دولتی",
    descriptionFa: "دولت یه پروژه بزرگ عمرانی اعلام کرد. کارگران ماهر می‌تونن استخدام بشن.",
    severity: "major",
    affectedSectors: ["construction", "services"],
    sectorHealthDelta: +2,
    salaryImpact: +0.08,
    jobDemandDelta: +8,
    investmentImpact: +0.05,
    durationDays: 6,
  },

  // ── Retail / Consumer ──
  {
    id: "norouz_rush",
    emoji: "🌸",
    titleFa: "هجوم خرید نوروزی",
    descriptionFa: "همه دارن خرید نوروزی می‌کنن. فروشگاه‌ها شلوغن و تقاضا بالاست.",
    severity: "minor",
    affectedSectors: ["retail", "services"],
    sectorHealthDelta: +3,
    salaryImpact: +0.05,
    jobDemandDelta: +6,
    investmentImpact: 0,
    durationDays: 5,
    triggerWaves: ["retail_holiday"],
    missionEventTag: "retail_event",
  },
  {
    id: "import_ban",
    emoji: "🚫",
    titleFa: "محدودیت واردات",
    descriptionFa: "دولت واردات کالا رو محدود کرد. کالاها کمیاب و گرون شدن.",
    severity: "major",
    affectedSectors: ["retail", "manufacturing"],
    sectorHealthDelta: -2,
    salaryImpact: -0.04,
    jobDemandDelta: -3,
    investmentImpact: -0.1,
    durationDays: 5,
    missionEventTag: "inflation_event",
  },

  // ── Manufacturing / Industry ──
  {
    id: "factory_strike",
    emoji: "✊",
    titleFa: "اعتصاب کارخانه",
    descriptionFa: "کارگران کارخانه اعتصاب کردن. تولید متوقف شده و قیمت‌ها داره می‌ره بالا.",
    severity: "crisis",
    affectedSectors: ["manufacturing", "retail"],
    sectorHealthDelta: -4,
    salaryImpact: -0.06,
    jobDemandDelta: -5,
    investmentImpact: -0.08,
    durationDays: 4,
    triggerWaves: ["recession"],
  },
  {
    id: "export_deal",
    emoji: "🤝",
    titleFa: "قرارداد صادراتی بزرگ",
    descriptionFa: "ایران یه قرارداد صادراتی بزرگ امضا کرد. تولید داخلی رونق گرفته.",
    severity: "major",
    affectedSectors: ["manufacturing", "construction"],
    sectorHealthDelta: +3,
    salaryImpact: +0.08,
    jobDemandDelta: +5,
    investmentImpact: +0.12,
    durationDays: 5,
    triggerWaves: ["manufacturing_revival"],
  },

  // ── Services / General ──
  {
    id: "energy_crisis",
    emoji: "⚡",
    titleFa: "بحران برق",
    descriptionFa: "خاموشی‌های گسترده تولید و خدمات رو مختل کرده. همه بخش‌ها آسیب دیدن.",
    severity: "crisis",
    affectedSectors: ["tech", "manufacturing", "services"],
    sectorHealthDelta: -3,
    salaryImpact: -0.07,
    jobDemandDelta: -4,
    investmentImpact: -0.15,
    durationDays: 4,
    triggerWaves: ["recession"],
    missionEventTag: "crisis_event",
  },
];
